### ISSUE TITLE
An error for 'tries to require `react-native`

### ISSUE THREAD

**Issue by wangjianhuiwita** [ShiYuanjun-Tim/react-native-checkboxgroup#1]
hello,
 The following errors when i added the 'react-native-checkboxgroup'.The errors as shown below:
error: bundling failed: ambiguous resolution: module `/Users/admin/WorkSpace/xxx/index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/admin/WorkSpace/xxx/node_modules/react-native-checkboxgroup/node_modules/react-native/package.json`
  * `/Users/admin/WorkSpace/xxx/node_modules/react-native/package.json`.
Development environment ：react-native 0.52.0
and it is Mac environment.

**Comment by ShiYuanjun-Tim** [comment]
sorry for response so later for some reasons.
it is the dependency problem, i have moved the react-native  as devDep it is fixed.

**Comment by ShiYuanjun-Tim** [comment]
please try version 1.3.1
